# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdbec3fd50d25befacf9177f2c3705b89116d7041c0bb5a1c5a8c7a75bca573b627f7f826f4988b28791cd941fc93477e2fe3062bf4cbb4fb16ebea28e88ffc4

test:
  secret_key_base: 8c3cc03ef980de09cf0a4d44474877de73721d782af683931daec81d900575fbeb713b3da9b643e01e5d90a723c360543e0906bed82bfecb47e07db48332ccdc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
